# Generated by Django 5.1.6 on 2025-03-23 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_generalsettings_generalsetting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generalsetting",
            old_name="updated_data",
            new_name="updated_date",
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
