# Generated by Django 5.1.6 on 2025-05-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('order',), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('start_date',), 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('start_date',), 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ('order',), 'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Açıklama metni için.', verbose_name='Description'),
        ),
    ]
