# Generated by Django 5.1.6 on 2025-05-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_document_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap ikon sınıfı (örneğin: bi-code-slash)', max_length=50),
        ),
    ]
